[package]
name = "rust_d3_array"
version = "0.1.0"
authors = ["martin frances <martinfrances107@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
geo="0.14.2"
num-traits="0.2.12"

[dev-dependencies]
pretty_assertions = "0.6.1"